### ISSUE TITLE
Getting "Cannot read property 'meta' of undefined " error 

### ISSUE THREAD

**Issue by Riaan-ZA** [vuefront/vuefront#28]
I've installed the wordpress pluggin on a clean wordpress install, with a clean woocommerce install and the woocommerce sample data loaded. I have the "CMS Connect URL " generated there and used it in my vuefront installation step. When I run build it run through the compilation process and then the page loading hangs after that. In the terminal I get the following:

```
ApolloClient networkError                                                                                                                                          13:29:54
undefined 
```
and

```
 ERROR  Cannot read property 'meta' of undefined                                                                                                                   13:31:54

  at VueComponent.handleLoadData (18.js:94:27)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at async server.js:2880:9
```

**Comment by lrush85** [comment]
Same

**Comment by Jorgu5** [comment]
same

**Comment by madridMMadrid** [comment]
Проблема не решена, у меня ничего не собирается и не билдится, кнопка Generate в https://vuefront.com/account/cms# так и не работает(((

**Comment by joker506** [comment]
есть какое-нибудь решение?

**Comment by joker506** [comment]
@madridMMadrid привет!

**Comment by joker506** [comment]
@madridMMadrid привет! Получилось решить как-нибудь проблему?

**Comment by veselinvelkov** [comment]
same
